# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the 5.6.1_30362.20181109_COEX20180928-6a6a branch
  push:
    branches: [ create-release ]
  pull_request:
    branches: [ create-release ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      
      - name: Install dependencies
        run: sudo apt install dkms debhelper

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          VER=$(sed -n 's/\PACKAGE_VERSION="\(.*\)"/\1/p' dkms.conf)
          sudo rsync -rvhP ./ /usr/src/rtl88x2bu-${VER}
          sudo dkms add -m rtl88x2bu -v ${VER}
          sudo dkms mkdeb -m rtl88x2bu -v ${VER}
